### ISSUE TITLE
circle.relate(polygon) incorrect

### ISSUE THREAD

**Issue by elijahiuu** [locationtech/spatial4j#127]
I have a circle intersecting simple triangle. The circle is intersecting on a segment and is nowhere close to triangle's vertices. Does spatial4j break polygons into segments to check for intersection?

```java
@Test
    public void spacial4JTest() throws Exception {
    SpatialContext ctx = JtsSpatialContext.GEO;
    JtsGeometry triangle = (JtsGeometry) ctx.readShapeFromWkt("POLYGON ((-95.35510540008545 29.888057687626, -95.33287525177002 29.888169310455122, -95.3442907333374 29.87819717794521, -95.35510540008545 29.888057687626))");
    Circle circle500m = ctx.makeCircle(-95.34493178129196, 29.888294885988515,
            DistanceUtils.dist2Degrees(
                0.5, // 500m
                DistanceUtils.EARTH_MEAN_RADIUS_KM
            ));

      sect = circle100m.relate(triangle);
      System.out.println("relationship: " + sect); // relationship: DISJOINT
}
```

![image](https://cloud.githubusercontent.com/assets/7199597/11999945/9190de34-aa98-11e5-9a0e-d21ef3f88120.png)

**Comment by yohanakh** [comment]
I have the same issue with LineString #128

**Comment by dsmiley** [comment]
This and #128 are essentially the same bug.  Namely, JtsGeometry.relate(Circle) is fundamentally flawed.  After it's done looping the coordinates possibly looking for an easy "intersects" (some vertices inside, some outside the circle), it should fall back on converting the circle to a Geometry via JtsSpatialContext.getGeometryFrom(circle) and then relating with that.
Thank for reporting this.

**Comment by yohanakh** [comment]
Do you have a release date for the next version (that will include the fix)?
Thanks!

**Comment by elijahiuu** [comment]
How about something like this? http://bl.ocks.org/mbostock/4218871 
They break down polygon into lines and do simple point-to-line distance calc. This would require converting lat/lon coordinates to a cartesian (UTM) first. 

Is this better or worse than converting circle into 32..100 point polygon with getGeometryFrom(circle) ?

For the most part I need to compute intersections on the scale of 1m - 100m in the US and Alaska.

**Comment by dsmiley** [comment]
Just as I had wrote my first response (then went to sleep), I thought of what you suggested @elijahiuu -- point-to-line distance calculations.

Good point using a projection for better accuracy.

I just fear this will all take longer than I have time to do myself right now.  But I'm very confident in JtsSpatialContext.getGeometryFrom(circle) working.  If you can submit a pull request for the point-to-line based solution then I'll work with you on that and get it in; otherwise I'll go with the simpler (albeit probably slower route) of JtsSpatialContext.getGeometryFrom(circle).

I want to get a release out in January.  Later this week or next I'm planning to do a spike of activity including adopting Geo3D as an alternative to JTS.  Geo3D should give an accurate answer to this polygon-circle intersection with no projections.
