### ISSUE TITLE
Handling x coordinate which is greater than 360

### ISSUE THREAD

**Issue by yadavan88** [locationtech/spatial4j#148]
Hi,
_First of all, I do not think this is actually a bug, but would be nice if it's supported._

Is it possible to handle coordinate like `(436.234, 12.769)` as `(76.234,12.769)` by reducing 360 (or its multiples) from 436.234. 
I have encountered this issue in one of the applications using _leaflet_. In leaflet, if you zoom out, the same world map keeps repeating and the x cordinate in the next  _world map_ will be + or - 360 with the current map. 
Someone had created the location in 436 coordinate and was giving issue while parsing in spatial4j. 

 This leaflet issue is posted [here](https://github.com/Leaflet/Leaflet/issues/1885).

In anyway, is it possible to handle this kind of scenario in spatial4j ?

**Comment by dsmiley** [comment]
Hi,
There is a setting on `SpatialContextFactory`: `normWrapLongitude` which defaults to false because I think it's most likely buggy software somewhere else that would generate this circumstance, thus people should try and fix the root cause.  But of course you might not be able to do that (easily) or have a difference of opinion, so it's a setting.

**Comment by yadavan88** [comment]
Hi @dsmiley , thank you very much for the quick reply.
