### ISSUE TITLE
How to calculate distance between two locations in meters?

### ISSUE THREAD

**Issue by alan-czajkowski** [locationtech/spatial4j#218]
between 2 GPS latitude and longitude positions

**Comment by dsmiley** [comment]
Hi,
See https://github.com/locationtech/spatial4j/blob/master/src/test/java/org/locationtech/spatial4j/distance/TestDistances.java
Haversine is typical.

If computing a geospatial distance is all you want to do, then I suggest copying the algorithm (from here or Stackoverflow) instead of adding a dependency.
